version: "3"

services:
  titan:
    build: 
      context: .
      dockerfile: titan.Dockerfile
    working_dir: /home/node/app
    # ports:
    #   - 3000:3000
    entrypoint: [ "npm", "run",  "dev" ]
    environment:
      - WATCHPACK_POLLING=true
        
  zeus:
    build: 
      context: .
      dockerfile: zeus.Dockerfile
    working_dir: /home/node/app
    volumes:
      - ./zeus:/home/node/app
    ports:
      - 3000:3000
    entrypoint: [ "npm", "run",  "dev" ]
    environment:
      - WATCHPACK_POLLING=true

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80